name: pedidos_front
description: "Frontend para Orders API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ Iconos de estilo iOS
  cupertino_icons: ^1.0.8

  # ğŸ”¹ HTTP client para conectar con la API REST
  http: ^1.2.2

  # ğŸ”¹ Animaciones suaves y transiciones
  flutter_animate: ^4.5.0

  # ğŸ”¹ Manejo de estados (opcional pero Ãºtil)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
